[package]
name = "munge-sys"
version = "0.2.0"
authors = ["Dan Søndergaard <das@birc.au.dk>"]
edition = "2018"
keywords = ["ffi", "snappy"]
description = "Native bindings to libmunge"

build = "build.rs"
links = "munge"

[dependencies]
libc = "0.2.60"

[build-dependencies]
pkg-config = "0.3"
