name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Fix permissions for munge
      run: sudo chmod -R 700 /etc
    
    - name: Install munge
      run: sudo apt-get update -y -qq && sudo apt-get install -y munge
    - name: Test that munge works
      run: munge -n | unmunge
      
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
